# Generated by Django 5.1.2 on 2025-01-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_inventory_current_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
