# Generated by Django 5.1.2 on 2025-01-12 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('Inventory_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=255)),
                ('ItemDescription', models.TextField()),
                ('UnitOfMeasure', models.CharField(max_length=50)),
                ('PurchasePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ReorderLevel', models.IntegerField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Perishable', models.BooleanField(default=False)),
                ('DaysBeforeExpiry', models.IntegerField(blank=True, null=True)),
                ('Current_Stock', models.IntegerField(default=0)),
                ('Expired', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_inventory',
            },
        ),
        migrations.CreateModel(
            name='KitchenResource',
            fields=[
                ('KitchenResource_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=255)),
                ('ItemDescription', models.TextField(blank=True, null=True)),
                ('ItemCategory', models.CharField(max_length=100)),
                ('Current_Stock', models.IntegerField(default=0)),
                ('ReorderLevel', models.IntegerField(default=0)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('QuantityToRepair', models.IntegerField(default=0)),
                ('Status', models.CharField(default='In Use', max_length=50)),
            ],
            options={
                'db_table': 'kitchen_resources',
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('Category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'material_categories',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('Resource_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=255)),
                ('ItemDescription', models.TextField(blank=True, null=True)),
                ('ItemCategory', models.CharField(max_length=100)),
                ('Current_Stock', models.IntegerField(default=0)),
                ('ReorderLevel', models.IntegerField(default=0)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('QuantityToRepair', models.IntegerField(default=0)),
                ('Status', models.CharField(default='In Use', max_length=50)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('Waste_ID', models.AutoField(primary_key=True, serialize=False)),
                ('IngredientName', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=50)),
                ('QuantityLost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UnitOfMeasurement', models.CharField(max_length=50)),
                ('CauseOfLoss', models.TextField()),
                ('DateOfIncident', models.DateTimeField()),
                ('AssociatedCosts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ActionTaken', models.TextField()),
            ],
            options={
                'db_table': 'waste_records',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('Ingredient_ID', models.AutoField(primary_key=True, serialize=False)),
                ('IngredientName', models.CharField(max_length=255)),
                ('ItemUnitMeasure', models.CharField(max_length=50)),
                ('MeasureCount', models.IntegerField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Inventory_ID', models.ForeignKey(db_column='Inventory_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='ItemCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materialcategory'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductDescription', models.TextField()),
                ('ProductCategory', models.CharField(max_length=100)),
                ('ProductImage', models.ImageField(upload_to='product_images/')),
                ('PurchasePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Ingredients', models.ManyToManyField(blank=True, to='api.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('ProductOrder_ID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderStatus', models.CharField(max_length=50)),
                ('OrderNumber', models.CharField(max_length=50)),
                ('CustomerName', models.CharField(max_length=255)),
                ('TableNumber', models.CharField(max_length=10)),
                ('OrderPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EstimatedPrepTime', models.IntegerField()),
                ('Products_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Supplier_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SupplierName', models.CharField(max_length=255)),
                ('SupplierDesc', models.TextField(blank=True, null=True)),
                ('SupplierNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('Status', models.CharField(default='Active', max_length=50)),
                ('MinOrderQty', models.IntegerField(default=0)),
                ('PaymentTerms', models.CharField(blank=True, max_length=100, null=True)),
                ('DeliveryTerms', models.CharField(blank=True, max_length=100, null=True)),
                ('Materials', models.ManyToManyField(blank=True, to='api.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('OrderStatus', models.CharField(max_length=50)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventory')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
    ]
