# Generated by Django 5.1.2 on 2025-01-09 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='ItemCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materialcategory'),
        ),
    ]
