# Generated by Django 5.1.2 on 2025-01-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='MeasureCount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
