# Generated by Django 5.1.2 on 2024-10-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_supplier_contractend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='DeliveryTerms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Order_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.order'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='PaymentTerms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='SupplierDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='SupplierNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
