# Generated by Django 5.1.2 on 2025-01-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_inventory_itemcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('Waste_ID', models.AutoField(primary_key=True, serialize=False)),
                ('IngredientName', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=50)),
                ('QuantityLost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UnitOfMeasurement', models.CharField(max_length=50)),
                ('CauseOfLoss', models.TextField()),
                ('DateOfIncident', models.DateTimeField()),
                ('AssociatedCosts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ActionTaken', models.TextField()),
            ],
            options={
                'db_table': 'waste_records',
            },
        ),
    ]
