# Generated by Django 5.1.2 on 2025-01-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='CheckoutMethod',
            field=models.CharField(choices=[('COD', 'Cash-On-Delivery'), ('GCASH', 'Gcash'), ('PAYMAYA', 'PayMaya'), ('DEBIT_CREDIT', 'Debit/Credit Card')], default='COD', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
    ]
