# Generated by Django 5.1.2 on 2025-01-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_waste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='SupplierNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
