# Generated by Django 5.1.2 on 2025-01-13 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ingredient_measurecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productcategory'),
        ),
    ]
