# Generated by Django 5.1.2 on 2025-01-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_checkoutmethod_alter_supplier_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='CheckoutMethod',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash-On-Delivery'), ('gcash', 'Gcash'), ('paymaya', 'PayMaya'), ('credit_card', 'Debit/Credit Card')], default='cash_on_delivery', max_length=50),
        ),
    ]
