# Generated by Django 5.1.2 on 2024-10-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_supplier_alter_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='Order_ID',
        ),
        migrations.AddField(
            model_name='supplier',
            name='Materials',
            field=models.ManyToManyField(blank=True, to='api.inventory'),
        ),
    ]
