# Generated by Django 5.1.2 on 2025-01-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_checkoutmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Current_Stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
