# Generated by Django 5.1.2 on 2024-10-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_supplier_order_id_supplier_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Ingredient_ID',
        ),
        migrations.AddField(
            model_name='product',
            name='Ingredients',
            field=models.ManyToManyField(blank=True, to='api.ingredient'),
        ),
    ]
