# Generated by Django 5.1.2 on 2025-01-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
