# Generated by Django 5.1.2 on 2024-11-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_product_ingredient_id_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='DaysBeforeExpiry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='Perishable',
            field=models.BooleanField(default=False),
        ),
    ]
