# Generated by Django 5.1.2 on 2024-11-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_supplier_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('Resource_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=255)),
                ('ItemDescription', models.TextField(blank=True, null=True)),
                ('ItemCategory', models.CharField(max_length=100)),
                ('Current_Stock', models.IntegerField(default=0)),
                ('ReorderLevel', models.IntegerField(default=0)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
    ]
