# Generated by Django 5.1.2 on 2024-12-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_kitchenresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='Expired',
            field=models.BooleanField(default=False),
        ),
    ]
