# Generated by Django 5.1.2 on 2025-01-04 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_inventory_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='Ingredient_ID',
            field=models.AutoField(db_column='Ingredient_ID', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Ingredient_ID',
            new_name='ingredient_id',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='IngredientName',
            field=models.CharField(db_column='IngredientName', max_length=255),
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='IngredientName',
            new_name='ingredientname',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ItemUnitMeasure',
            field=models.CharField(db_column='ItemUnitMeasure', max_length=50),
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ItemUnitMeasure',
            new_name='itemunitmeasure',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='MeasureCount',
            field=models.IntegerField(db_column='MeasureCount'),
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='MeasureCount',
            new_name='measurecount',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='DaysBeforeExpiry',
            field=models.IntegerField(blank=True, db_column='DaysBeforeExpiry', null=True),
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='DaysBeforeExpiry',
            new_name='daysbeforeexpiry',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Inventory_ID',
            field=models.AutoField(db_column='Inventory_ID', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Inventory_ID',
            new_name='inventory_id',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ItemCategory',
            field=models.CharField(db_column='ItemCategory', max_length=100),
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='ItemCategory',
            new_name='itemcategory',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ItemDescription',
            field=models.TextField(db_column='ItemDescription'),
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='ItemDescription',
            new_name='itemdescription',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ItemName',
            field=models.CharField(db_column='ItemName', max_length=255),
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='ItemName',
            new_name='itemname',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ReorderLevel',
            field=models.IntegerField(db_column='ReorderLevel'),
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='ReorderLevel',
            new_name='reorderlevel',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='UnitOfMeasure',
            field=models.CharField(db_column='UnitOfMeasure', max_length=50),
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='UnitOfMeasure',
            new_name='unitofmeasure',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='Created_At',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='Inventory_ID',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Created_At',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Current_Stock',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Expired',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='Perishable',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='PurchasePrice',
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='api_ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='created_at',
            field=models.DateTimeField(db_column='Created_At', default=2023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='inventory_id',
            field=models.ForeignKey(db_column='Inventory_ID', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='api.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(db_column='Created_At', default=2023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='current_stock',
            field=models.IntegerField(db_column='Current_Stock', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='expired',
            field=models.BooleanField(db_column='Expired', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='perishable',
            field=models.BooleanField(db_column='Perishable', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchaseprice',
            field=models.DecimalField(db_column='PurchasePrice', decimal_places=5, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
