# Generated by Django 5.1.2 on 2025-01-04 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_inventory_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='Inventory_ID',
            field=models.ForeignKey(db_column='Inventory_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.inventory'),
        ),
    ]
