# Generated by Django 5.1.2 on 2025-01-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_ingredient_inventory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('Category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'material_categories',
            },
        ),
    ]
