# Generated by Django 5.1.2 on 2025-01-04 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_ingredient_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredientname',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='itemunitmeasure',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='measurecount',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='daysbeforeexpiry',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='itemcategory',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='itemdescription',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='itemname',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='perishable',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='purchaseprice',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='reorderlevel',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='unitofmeasure',
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table=None,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='Created_At',
            field=models.DateTimeField(auto_now_add=True, default=2023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='Ingredient_ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='IngredientName',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='Inventory_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ItemUnitMeasure',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='MeasureCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='Created_At',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='Current_Stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='DaysBeforeExpiry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='Expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='Inventory_ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='ItemCategory',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='ItemDescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='ItemName',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='Perishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='PurchasePrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='ReorderLevel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='UnitOfMeasure',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
