# Generated by Django 5.1.2 on 2025-01-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_materialcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenresource',
            name='QuantityToRepair',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kitchenresource',
            name='Status',
            field=models.CharField(default='In Use', max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='QuantityToRepair',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='Status',
            field=models.CharField(default='In Use', max_length=50),
        ),
    ]
