# Generated by Django 5.1.2 on 2025-01-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
    ]
